---
timeout: 0.5
refresh: 0.8
refresh_screen: 0.8
ICMP: "ICMP"
ping_cmd: "ping -c 1 -w 1 "
box:
    label: "Ping"
    width: 30
    margin_x: 3
    margin_y: 1
    height: 4
    start_x: 5
    start_y: 5
node:
    ok: "OK"
    ko: "KO"
msg: "Press ESC to EXIT"
progress:
        0: '-'
        1: '\'
        2: '|'
        3: '/'
script:
    bin: "bin/pyt-ping.py"
    description: "Ping tool..."
...
